version: '3.8'

services:
    app:
        build: ./app
        ports:
            - "8000:8000"
        env_file:
            - .env
        volumes:
            - ./app:/app
        restart: unless-stopped

    nginx:
        image: nginx:1.23.3
        # монтируем директорию nginx и сертификат с ключом
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /etc/ssl/mosaction.ru.crt:/etc/ssl/mosaction.ru.crt
            - /etc/ssl/mosaction.ru.key:/etc/ssl/mosaction.ru.key
            # - ./nginx/cert.pem:/etc/cert.pem
            # - ./nginx/key.pem:/etc/key.pem
        ports:
            - "80:80"
            - "443:443"
        restart: unless-stopped

    # certbot:
    #     ports:
    #         - "6000:80"
    #     env_file:
    #         - .env
    #     # и снова мониторуем директорию nginx
    #     volumes:
    #         - ./nginx/:/etc/nginx/
    #     build:
    #         context: ./certbot
    #         dockerfile: Dockerfile
